version: '3'

services:
  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
   # networks:
     # - app_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    #depends_on:
      #- mongo
    environment:
      - MONGO_URL=mongodb+srv://alexsava0709:Metalica@cluster0.o5celo3.mongodb.net/
   # networks:
    #  - app_network
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    ports:
     - "80:80"
    # No custom Nginx configuration needed, use the default settings
    depends_on:
      - server

  #mongo:
   #image: mongo:latest
   #restart: always
    #networks:
     # - app_network

#networks:
 # app_network:
  #  driver: bridge
